/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 * Copyright 2010 BiBiServ Curator Team, http://bibiserv.cebitec.uni-bielefeld.de, 
 * All rights reserved.
 * 
 * The contents of this file are subject to the terms of the Common
 * Development and Distribution License("CDDL") (the "License"). You 
 * may not use this file except in compliance with the License. You can 
 * obtain a copy of the License at http://www.sun.com/cddl/cddl.html
 * 
 * See the License for the specific language governing permissions and 
 * limitations under the License.  When distributing the software, include 
 * this License Header Notice in each file.  If applicable, add the following 
 * below the License Header, with the fields enclosed by brackets [] replaced
 *  by your own identifying information:
 * 
 * "Portions Copyrighted [year] [name of copyright owner]"
 * 
 * Contributor(s):
 * 
 */
package de.unibi.techfak.bibiserv.tools.rnaalishapes.web;

import de.unibi.cebitec.bibiserv.util.validate.ValidationException;
import de.unibi.techfak.bibiserv.cms.Texample.Prop;
import de.unibi.techfak.bibiserv.tools.rnaalishapes.Utilities;
import de.unibi.techfak.bibiserv.util.Pair;
import de.unibi.techfak.bibiserv.web.beans.session.MessagesInterface;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.faces.event.ActionEvent;
import org.apache.log4j.Logger;

/**
 * This is a autogenerated bean input template class for function <i>rnaalishapes_function_convert_param</i>
 *
 * @author Daniel Hagemeier - dhagemei[aet]cebitec.uni-bielefeld.de
 *         Armin Toepfer - atoepfer[aet]cebitec.uni-bielefeld.de
 *         Jan Krueger - jkrueger[aet]cebitec.uni-bielefeld.de
 */
 public class rnaalishapes_function_convert_param   { 

     private final static Logger log = Logger.getLogger(rnaalishapes_function_convert_param.class);


    /* #########################################
     * #     DI method setMessages             #
     * ######################################### */
    private MessagesInterface messages;

    public void setMessages(MessagesInterface messages) {
        this.messages = messages;
    }
    
    /* #########################################
     * #     parameter default values          #
     * ######################################### */
    private static final String defaultValue_rnaalishapes_parameter_grammar="overdangle";
private static final String defaultValue_rnaalishapes_parameter_shape_level="5";
private static final String defaultValue_rnaalishapes_parameter_lonely_base_pairs="0";




public void reset(){
rnaalishapes_parameter_shape_level = defaultValue_rnaalishapes_parameter_shape_level;
}


public boolean defaultParams(){
if (true 
&& rnaalishapes_parameter_shape_level.equals(defaultValue_rnaalishapes_parameter_shape_level)
){
return true;
} else { return false; }
}



    /* #########################################
     * #     parameters are valid ?            #
     * ######################################### */
     public boolean isValid(){
        return true
                
                && valid_rnaalishapes_parameter_grammar
                
                && valid_rnaalishapes_parameter_shape_level
                
                && valid_rnaalishapes_parameter_lonely_base_pairs
                
                ;
    }
     
    /* ######################################
     * # example                            #
     * ######################################
     */
    public boolean checkAndSet(Prop p) {
        
        if (p.getIdref().equals("rnaalishapes_parameter_grammar")) {
            rnaalishapes_parameter_grammar = p.getValue();
            return true;
        }
        
        if (p.getIdref().equals("rnaalishapes_parameter_shape_level")) {
            rnaalishapes_parameter_shape_level = p.getValue();
            return true;
        }
        
        if (p.getIdref().equals("rnaalishapes_parameter_lonely_base_pairs")) {
            rnaalishapes_parameter_lonely_base_pairs = p.getValue();
            return true;
        }
        
        return false;
    }

     /* #########################################
     *          fault(=invalid) messages
     * ######################################### */
    private HashMap<String, String> faultmsg = new HashMap<String, String>();

    public String faultmsg(String key) {
        return faultmsg.get(key);
    }

    public boolean faultmsgExist(String key) {
        return faultmsg.containsKey(key);
    }

    public void addFaultmsg(String key, String value) {
        faultmsg.put(key, value);
    }

    /**
     * Return a Parameter list of all set (non-empty) parameters.
     *
     * @return List<Pair<parameter_id<String>,parameter_value<String>>
     */
    public List<Pair<String, String>> getParameterList() {
        List<Pair<String, String>> pairlist = new ArrayList<Pair<String, String>>();
        
        if (!rnaalishapes_parameter_grammar.isEmpty()) {
            pairlist.add(new Pair<String, String>("rnaalishapes_parameter_grammar", rnaalishapes_parameter_grammar));
        }
        
        if (!rnaalishapes_parameter_shape_level.isEmpty()) {
            pairlist.add(new Pair<String, String>("rnaalishapes_parameter_shape_level", rnaalishapes_parameter_shape_level));
        }
        
        if (!rnaalishapes_parameter_lonely_base_pairs.isEmpty()) {
            pairlist.add(new Pair<String, String>("rnaalishapes_parameter_lonely_base_pairs", rnaalishapes_parameter_lonely_base_pairs));
        }
        

        return pairlist;
    }


    /* #########################################
     * #  parameter getter, setter, validator  #
     * ######################################### */
     /*--- parameter 'rnaalishapes_parameter_grammar' --- */
private boolean help_rnaalishapes_parameter_grammar = false;
public boolean isHelp_rnaalishapes_parameter_grammar(){
 return help_rnaalishapes_parameter_grammar;
 }
public void helpAction_rnaalishapes_parameter_grammar(ActionEvent e){
help_rnaalishapes_parameter_grammar = !help_rnaalishapes_parameter_grammar;
} 
private String rnaalishapes_parameter_grammar=defaultValue_rnaalishapes_parameter_grammar;
private boolean valid_rnaalishapes_parameter_grammar= true;
public String getRnaalishapes_parameter_grammar(){
return rnaalishapes_parameter_grammar;
}
public void setRnaalishapes_parameter_grammar(String input){
if (!rnaalishapes_parameter_grammar.equals(input)) {
try {
Utilities.validate_rnaalishapes_parameter_grammar(input,messages);
this.rnaalishapes_parameter_grammar=input;
faultmsg.remove("rnaalishapes_parameter_grammar_rnaalishapes_function_convert");
valid_rnaalishapes_parameter_grammar = true;
return;
} catch (ValidationException e){
faultmsg.put("rnaalishapes_parameter_grammar_rnaalishapes_function_convert",e.getMessage());}
valid_rnaalishapes_parameter_grammar = false;
}
}
/*--- parameter 'rnaalishapes_parameter_shape_level' --- */private boolean help_rnaalishapes_parameter_shape_level = false;public boolean isHelp_rnaalishapes_parameter_shape_level(){ return help_rnaalishapes_parameter_shape_level;}public void helpAction_rnaalishapes_parameter_shape_level(ActionEvent e){help_rnaalishapes_parameter_shape_level = !help_rnaalishapes_parameter_shape_level;}private String rnaalishapes_parameter_shape_level = defaultValue_rnaalishapes_parameter_shape_level;
private boolean valid_rnaalishapes_parameter_shape_level = true;
public String getRnaalishapes_parameter_shape_level(){return rnaalishapes_parameter_shape_level;}public void setRnaalishapes_parameter_shape_level(String input){
if (!rnaalishapes_parameter_shape_level.equals(input)) {
this.rnaalishapes_parameter_shape_level=input;
try {
if (!input.isEmpty()) {
int tmp =  Integer.parseInt(input);
Utilities.validate_rnaalishapes_parameter_shape_level(tmp,messages);
}
//remove possible previous set faultmsg
faultmsg.remove("rnaalishapes_parameter_shape_level_rnaalishapes_function_convert");
valid_rnaalishapes_parameter_shape_level = true;
return;
}catch (NumberFormatException e) {
faultmsg.put("rnaalishapes_parameter_shape_level_rnaalishapes_function_convert",messages.property("de.unibi.techfak.bibiserv.bibimainapp.input.param.num.INTEGER"));
}catch (ValidationException e) {
faultmsg.put("rnaalishapes_parameter_shape_level_rnaalishapes_function_convert",e.getMessage());
}
valid_rnaalishapes_parameter_shape_level = false;}
}
/*--- parameter 'rnaalishapes_parameter_lonely_base_pairs' --- */
private boolean help_rnaalishapes_parameter_lonely_base_pairs = false;
public boolean isHelp_rnaalishapes_parameter_lonely_base_pairs(){
 return help_rnaalishapes_parameter_lonely_base_pairs;
 }
public void helpAction_rnaalishapes_parameter_lonely_base_pairs(ActionEvent e){
help_rnaalishapes_parameter_lonely_base_pairs = !help_rnaalishapes_parameter_lonely_base_pairs;
} 
private String rnaalishapes_parameter_lonely_base_pairs=defaultValue_rnaalishapes_parameter_lonely_base_pairs;
private boolean valid_rnaalishapes_parameter_lonely_base_pairs= true;
public String getRnaalishapes_parameter_lonely_base_pairs(){
return rnaalishapes_parameter_lonely_base_pairs;
}
public void setRnaalishapes_parameter_lonely_base_pairs(String input){
if (!rnaalishapes_parameter_lonely_base_pairs.equals(input)) {
try {
Utilities.validate_rnaalishapes_parameter_lonely_base_pairs(input,messages);
this.rnaalishapes_parameter_lonely_base_pairs=input;
faultmsg.remove("rnaalishapes_parameter_lonely_base_pairs_rnaalishapes_function_convert");
valid_rnaalishapes_parameter_lonely_base_pairs = true;
return;
} catch (ValidationException e){
faultmsg.put("rnaalishapes_parameter_lonely_base_pairs_rnaalishapes_function_convert",e.getMessage());}
valid_rnaalishapes_parameter_lonely_base_pairs = false;
}
}

    
}
